receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024
  
  tail_sampling:
    decision_wait: 10s
    num_traces: 100
    expected_new_traces_per_sec: 10
    policies:
      # keep failed jobs
      - name: errors-policy
        type: status_code
        status_code:
          status_codes: [ERROR]
      
      # keep slow jobs(30s is demo only)
      - name: slow-jobs
        type: latency
        latency:
          threshold_ms: 30000
      
      # adjust based on backend capacity
      - name: probabilistic-policy
        type: probabilistic
        probabilistic:
          sampling_percentage: 20

exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling, batch]
      exporters: [otlp, debug]

